---
title: "Homework 5"
author: "Ziyu Chen"
date: "11/19/2021"
output: github_document
---
#R setup
```{r message=FALSE}
library(readxl)
library(tidyverse)
```


# Problem 1

_Read in the data_
```{r message=FALSE}
murder_raw = 
  read_csv(url("https://github.com/washingtonpost/data-homicides/raw/master/homicide-data.csv")) 
```

Murder_df has 52179 observations and 12 variables, including city, city_state, disposition, lat, lon, reported_date, state, uid, victim_age, victim_first, victim_last, victim_race, victim_sex. This dataset contains information about homicide cases in the United States. 

_Create the city_state variable,  find the murders count within the city_
```{r}
murder_new = murder_raw %>%
   mutate(city_state = paste(city, state, sep = ", ")) %>%
  group_by(city_state)


murder_total=
murder_new %>%
  group_by(city_state) %>%
  summarise(total = n())

murder_unsolved =
  murder_new %>%
  filter(disposition %in% c("Closed without arrest","Open/no arrest")) %>%
  group_by(city_state) %>%
  summarise(unsolved = n())

final = left_join(murder_total, murder_unsolved, by = "city_state")
  
  knitr::kable(final [1:10, ]) #showing the only first ten rows to make sure that the data are correct


```

